### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by jegnux**
`RxGesture` is a nice extension but suffers from many drawbacks : 

- It's not extendable : if you want to support a new `UIGestureRecognizer` subclass, you have to add an `enum case` and modify the `gesture()` method to support that case. It leads to an incredible method of 150+ lines. 

- `PanConfig` and `RotateConfig` are really weird. There are used to configure the gesture AND to emit gesture's values like `velocity`, `translation`, `rotation`, etc...

- `pan` and `rotation` gestures are automatically reused and `shareReplay()`. This could lead to unexpected behaviors. IMHO, it should be the API consumer to decide wether or not they want to `shareReplay()` their gesture recognizer.

- `enum cases` can't have default values. As a workaround, there was an extra case for some gestures (ex: `.tap` / `.tapNumberOfTimes`), but it's not really convenient nor extendable

This PR tries to address all of these points.

It's still `work in progress` : 
- [x] refactor support of iOS gesture recognizers
- [x] refactor support of macOS gesture recognizers
- [x] support all iOS native gesture recognizers
- [x] support all macOS native gesture recognizers
- [x] add method inline documentation
- [x] update `README.md`

Feel free to comment or suggest any modification to the proposed architecture 🤗

### CODE REVIEW

**Comment by icanzilb** [comment]
@JegnuX I see that you did a lot of work and that you've discarded the work so far on the code. The only way I see this working out is if you'd like to take over the support of repo - the ought to be at least one person who feels like releasing new versions and/or address issues (e.g. vs. redesigning the code from ground up and moving on to other stuff) ... If that sounds interesting I'll be glad to add you to the org

**Comment by fpillet** [comment]
@icanzilb I actually already added Jérôme to the org. The question we debated was whether it would be a better idea to make his rewrite a separate project. I don't think it's wise: we want the RxSwiftCommunity projects to provide a clear choice, not competing implementation of solutions.

What do you think?

**Comment by jegnux** [comment]
Hey @icanzilb, as @fpillet said, we debated wether we should make a separate project or refactor/rewrite this one, and we agreed on the fact that we should combine community efforts, not split them.

As you said, I rewrote a consequent part of the code, so if this PR is merged, of course I'll continue to work on this project and I'll help you to maintain it.

**Comment by icanzilb** [comment]
@fpillet @JegnuX yes I also agree it's better to have a single project instead of competing libraries. Since you two have worked on the ideas in this PR, you can polish it and merge it. If one or both of you would like to push releases to CP I can add you as authors

**Comment by icanzilb** [comment]
@JegnuX anything else you need help with before moving ahead with this?

**Comment by jegnux** [comment]
@icanzilb not really except some instructions about : 
- how make a new version (what will be the version number ? 0.3.0 ? 1.0.0 ?)
- how to update Cocoapods and Carthage specs
- should we do something special to help people migrate their code ?

I'll try to complete this PR this weekend as I'll have some free time.
Thanks again for your feedback 👍

**Comment by icanzilb** [comment]
* `1.0.0` would mean you really do not forsee many breaking changes, `0.3.0` means the library is still work in progress
* Carthage - no idea, CocoaPods - you just put in a new number in the .podspec file - I need your email address to add you to CocoaPods trunk so you can push the new version to CocoaPods
* migration - I'm not sure if we can do something, your code is completely different than what was there before so I don't think there is a way to help all existing users to migrate

**Comment by fpillet** [comment]
I haven't had the time to review your code, sorry Jerôme. Juggling with projects atm. Sorry about that.

**Comment by jegnux** [comment]
@icanzilb ok, thank you.
@fpillet no problem, I'll perform some changes this weekend to try to have a multiple gesture operator again (like `view.rx.gesture(.tap, .swipeUp, .swipeDown)`

**Comment by jegnux** [comment]
I think it's now out of `work in progress` and ready for a full review.
The diff is quite hard to read, I suggest you to checkout the branch and directly dive into the code.

**Comment by jegnux** [comment]
PS: this PR will let us close #19, #22, #27 and #29 🙂

**Comment by jegnux** [comment]
@icanzilb @fpillet Do think you'll be able to review the code this week ? It could be great to move forward on this :)

**Comment by icanzilb** [comment]
@JegnuX as I wrote earlier, since you guys worked on the refactor you two can merge it any time you decide. I don't feel like there's anything to review on my side

**Comment by fpillet** [comment]
Yup it's my duty to review. I'm on vacation this week (and sick as a dog :( ) but I'll free up some time ASAP. Don't worry Jérôme this will get merged soon -- I need this update to finalize a related tutorial.

**Comment by freak4pc** [comment]
Please do share the tutorial when you get there ;-) @fpillet 
Oh and, feel better soon!

**Pull request merged**
