### PR TITLE
disabling selection and editing of the text view in the demo app

### PR DESCRIPTION
**Pull request by waterskier2007**

### CODE REVIEW

**Comment by waterskier2007** [comment]
it's a simple PR, but I just noticed it in the demo app

**Comment by icanzilb** [comment]
it says `0 files changed` ?

**Comment by waterskier2007** [comment]
Yeah, something's going on. Should have been a change in the storyboard

**Comment by waterskier2007** [comment]
It shows the changes here: https://github.com/RxSwiftCommunity/RxGesture/compare/master...waterskier2007:master

I'm not sure what's going on...

**Comment by icanzilb** [comment]
have you pulled from this repo before sending the PR?

**Comment by waterskier2007** [comment]
Yes, and like my last comment said, it shows the difference there. I will close and re-pull

**Pull request closed without merging**
