### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by tomassliz**
This code is not needed anymore in the last CocoaPods version.

### CODE REVIEW

**Comment by freak4pc** [comment]
Uhm I'm not sure this actually needs to be part of the README since Cocoapods 1.2.0.beta.3 (latest) doesn't require it. If this was a version-wide issue, perhaps ... Is there really a necessity for that? :)

**Comment by tomassliz** [comment]
I have Cocoapods 1.1.1 and everything is ok without script from deleted part of README.

**Comment by icanzilb** [comment]
I would also ditch this paragraph. @tomassliz can you delete also the other note about being a pre-release software etc. just before the para you deleted?

**Comment by freak4pc** [comment]
Oh my bad I totally thought you _added_ this and not _removed_ it... Too early ;-)

**Comment by tomassliz** [comment]
@icanzilb Done.

**Comment by icanzilb** [comment]
thanks!

**Pull request merged**
