### PR TITLE
Update dependencies for RxSwift 4.4.0

### PR DESCRIPTION
**Pull request by clementleroy**

### CODE REVIEW

**Review by jegnux — APPROVED** [review]

**Comment by beloso** [comment]
Are there any plans to when this will be merged and released?

**Comment by jegnux** [comment]
@beloso now :)

**Comment by jegnux** [comment]
@beloso 
```
🚀  RxGesture (2.1.0) successfully published
 📅  November 7th, 18:25
 🌎  https://cocoapods.org/pods/RxGesture
```

**Comment by beloso** [comment]
Thank you very much. I've updated it in my project.

**Pull request merged**
