### PR TITLE
Swift 5.0 and Xcode 10.2

### PR DESCRIPTION
**Pull request by lm2343635**
This PR includes the followings:
- Fix the build warning after Xcode 10.2
- Update to Swift 5.0.

### CODE REVIEW

**Comment by SamHFrancis** [comment]
Since this PR was created, RxSwift 4.5 has been released. Maybe this PR should be updated to depend on that version.

**Comment by seanrucker** [comment]
The dependencies in the podspec prevent it from being compatible with the latest versions of RxSwift and RxCoccoa:

```ruby
s.dependency 'RxSwift', '~> 4.4.0'
s.dependency 'RxCocoa', '~> 4.4.0'
```

Changing them to this would solve the problem:

```ruby
s.dependency 'RxSwift', '~> 4.4'
s.dependency 'RxCocoa', '~> 4.4'
```

**Comment by dfmarulanda** [comment]
Any updates on this?

**Comment by lm2343635** [comment]
@Dfmarulanda 
Updated.

**Comment by dfmarulanda** [comment]
@jegnux

**Comment by jegnux** [comment]
RxGesture 2.2.0 is now available with RxSwift 4.5 and Swift 5 compatibility 😉

**Pull request merged**
